apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster-B
  region: us-east-1

nodeGroups:
  - name: ng-b
    instanceType: t3.medium
    desiredCapacity: 3 
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
