apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster-A
  region: us-east-1

nodeGroups:
  - name: ng-2
    instanceType: t3.large
    desiredCapacity: 3 
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
