apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster-B
  region: us-east-1

nodeGroups:
  - name: ng-b
    instanceType: t3.medium
    desiredCapacity: 2 
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c', 'us-east-1d']      