apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: gateway-production
  namespace: istio-system 
spec:
  # Secret names are always required.
  secretName: gateway-production-secret 
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  organization:
  - jetstack
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, USI SAN, or IP address is required.
  dnsNames:
  - gw1.gateway.k8sguru.info
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-production
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
